<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/06/22 13:44:26

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=freecrm',
  'username' => 'root',
  'password' => 'mksmksmks',
  'name' => 'doctrine',
)),);
